name: "Deploy da aplicação em MAIN VPS PRINCIPAL"
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Conectando via SSH e fazendo git pull na branch main"
        uses: appleboy/ssh-action@v0.1.0
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd /www/wwwroot/unseenpay.com/sistema/
            git fetch origin
            git reset --hard origin/main
            git checkout main
            git pull origin main
            php artisan migrate
            sudo chown -R www:www /www/wwwroot/unseenpay.com/sistema/